#!/usr/bin/env python3
from configparser import ConfigParser
import os
import json
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

icon_override = {
	"pcmanfm": "pcmanfm-qt",
	"imv":     "image-viewer",
}

def fetch(icon_name):
	if not icon_name:
		return

	icon_theme = Gtk.IconTheme.new()
	icon_theme.set_custom_theme("Papirus")
	if icon_name in icon_override:
		icon_name = icon_override[icon_name]
	icon = icon_theme.lookup_icon(icon_name, 32, 0)
	if icon:
		return icon.get_filename()
	else:
		return

def parse(path):
	if not (config := ConfigParser(interpolation=None)).read(path):
		return
	entry = config["Desktop Entry"]
	app_id = os.path.basename(path)
	app_id, e = os.path.splitext(app_id)

	return {
		"app":     app_id,
		"name":    entry["Name"],
		# "exec":    entry["Exec"],
		"generic": entry.get("GenericName"),
		"comment": entry.get("Comment"),
		"icon":    entry.get("Icon")
	}

def main():
	entries = []
	a = [f for r, d, files in os.walk("/usr/share/applications") for f in files if f.endswith(".desktop")]
	for f in a:
		entry = parse(f"/usr/share/applications/{f}")
		if entry:
			icon = fetch(entry.get("icon"))
			if icon:
				entry["icon"] = icon;
			entries.append(entry)
	print(json.dumps(entries), flush=True)

if __name__ == "__main__":
	main()
